[2024-05-04T11:41:06.872+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T11:41:06.923+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_order_dataset scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T11:41:06.966+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_order_dataset scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T11:41:06.966+0000] {taskinstance.py:2303} INFO - Starting attempt 5 of 5
[2024-05-04T11:41:07.012+0000] {taskinstance.py:2327} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_order_dataset> on 2024-05-03 00:00:00+00:00
[2024-05-04T11:41:07.032+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12544) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T11:41:07.033+0000] {standard_task_runner.py:63} INFO - Started process 12559 to run task
[2024-05-04T11:41:07.049+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_order_dataset', 'scheduled__2024-05-03T00:00:00+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmprkxktpbl']
[2024-05-04T11:41:07.050+0000] {standard_task_runner.py:91} INFO - Job 208: Subtask create_order_dataset
[2024-05-04T11:41:07.175+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.create_order_dataset scheduled__2024-05-03T00:00:00+00:00 [running]> on host d4c1d9b975b8
[2024-05-04T11:41:07.502+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_order_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-03T00:00:00+00:00'
[2024-05-04T11:41:07.504+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T11:41:07.519+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-04T11:41:07.524+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-05-04T11:41:07.570+0000] {bigquery.py:470} INFO - datasetId was not specified in `dataset_reference`. Will use default value order.
[2024-05-04T11:41:07.570+0000] {bigquery.py:470} INFO - projectId was not specified in `dataset_reference`. Will use default value project-capstone-422211.
[2024-05-04T11:41:07.570+0000] {bigquery.py:481} INFO - Creating dataset: order in project: project-capstone-422211 
[2024-05-04T11:41:07.957+0000] {bigquery.py:2045} INFO - Dataset order already exists.
[2024-05-04T11:41:07.974+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T11:41:07.982+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_order_dataset, execution_date=20240503T000000, start_date=20240504T114106, end_date=20240504T114107
[2024-05-04T11:41:08.031+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-04T11:41:08.051+0000] {taskinstance.py:3482} INFO - 9 downstream tasks scheduled from follow-on schedule check
[2024-05-04T11:41:08.058+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
